apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-product-rules
  namespace: openshift-monitoring
spec:
  groups:
  - name: product.rules
    rules:
    - expr: |
        sum by (product, type, version) (
          label_replace(
            label_replace(
              label_replace(
                kube_pod_labels{label_com_redhat_product_name=~".+"}
                    and on(pod,namespace) kube_pod_status_phase{phase="Running"},
                "product", "$1", "label_com_redhat_product_name", "(.*)"
              ),
              "version", "$1", "label_com_redhat_product_version", "(.*)"
            ),
            "type", "$1", "label_com_redhat_component_type", "(.*)"
          )
        )
      record: product:pod:sum
    - expr: |
        sum by (product) (
          label_replace(
            kube_pod_labels{label_ActiveMQArtemis=~".+"}
              and on(pod,namespace) kube_pod_status_phase{phase="Running"},
            "product", "activemq-artemis", "label_ActiveMQArtemis", "(.*)"
          )
        )
      record: product:pod:sum
    - expr: |
        sum by (product) (
          label_replace(
            kube_pod_labels{label_infinispan_cr=~".+"}
              and on(pod,namespace) kube_pod_status_phase{phase="Running"},
            "product", "data-grid", "label_infinispan_cr", "(.*)"
          )
        )
      record: product:pod:sum
    - expr: |
        sum by (version, namespace) (
          label_replace(
            kube_pod_labels{label_com_redhat_product_name="process-automation"}
              and on(pod,namespace) kube_pod_status_phase{phase="Running"},
            "version", "$1", "label_com_redhat_product_version", "(.*)"
          )
        )
      labels:
        product: process-automation
      record: product:pod:process_automation:sum
